### ISSUE TITLE
"Error executing vim.schedule lua callback: Vim:E976: Using a Blob as a String" with omni completion

### ISSUE THREAD

**Issue by MariaSolOs** [uga-rosa/ccc.nvim#101]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

When using omni completion via the builtin `i_CTRL-X_CTRL-O` command, the following error message is generated by this plugin:
```
Error executing vim.schedule lua callback: Vim:E976: Using a Blob as a String
stack traceback:
        [C]: in function 'matchlist'
        ...local/share/nvim/lazy/ccc.nvim/lua/ccc/utils/pattern.lua:37: in function 'find'
        ...o/.local/share/nvim/lazy/ccc.nvim/lua/ccc/picker/hex.lua:36: in function 'parse_color'
        .../.local/share/nvim/lazy/ccc.nvim/lua/ccc/highlighter.lua:311: in function 'update_picker'
        .../.local/share/nvim/lazy/ccc.nvim/lua/ccc/highlighter.lua:163: in function <.../.local/share/nvim/lazy/ccc.nvim/lua/ccc/highlighter.lua:161>
```

### Environments

`nvim` version: v0.10.0-dev-2384+g848fc8ede
OS: Both reproducible in macOS 14.3.1 (23D60) and Fedora Asahi Remix

### Minimal reproducible full config

_I'm sorry in advance for not using the provided template. I'm VERY unfamiliar with Vimscript, and I had lots of trouble building a proper minimal configuration for this issue. Yet I thrive on submitting high-quality and helpful issues, hence the configuration below is written in Lua (please pardon my skill issues) and has been carefully tested to truly represent a minimal setup. If this represents an issue for you, please lmk and I'll accommodate._

```lua
local plugins = {
  ccc = 'https://github.com/uga-rosa/ccc.nvim.git',
  lspconfig = 'https://github.com/neovim/nvim-lspconfig.git',
  lsp_compl = 'https://github.com/mfussenegger/nvim-lsp-compl.git',
}

-- Make sure that the executable for lua_lsp in available in your path!
-- E.g.: When installing `lua_ls` with Mason: vim.env.PATH = vim.env.PATH .. ':' .. vim.fn.stdpath 'data' .. '/mason/bin'

for name, url in pairs(plugins) do
  local install_path = 'repro/' .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path .. ',' .. vim.o.runtimepath
end

require'lspconfig'.lua_ls.setup { on_attach = require 'lsp_compl'.attach }
```

### Steps to reproduce

1. Inside a folder called `repro` create the provided `nvim` configuration file called `minimal.lua`.
2. Run `nvim --clean -u minimal.lua minimal.lua -c "normal10G"`.
3. Type the following commands: `o<Ctrl-x><Ctrl-o><Tab><Ctrl-x><Ctrl-o>`.
4. Observe the generated error message.

### Expected behavior

For this plugin to not affect omni completion.

### Actual behavior

A disruptive error message affects the omni completion experience.

**Comment by uga-rosa** [comment]
Putting in workaround is good in itself, but you should report this to nvim-lsp-compl as well. This phenomenon is caused by the inclusion of `\n` (`^@`) in a line, so that the string is no longer interpreted as a string.

**Comment by MariaSolOs** [comment]
@uga-rosa Interesting, that's a great point.

In fact, this makes me realize that there might be a bug in Neovim's completion/omnifunc implementation. I'll make my "solution" a draft, and keep this issue as a reference and close it once I identity that the culprit is the editor itself.

**Comment by MariaSolOs** [comment]
@uga-rosa okay after reaching out to other Neovim maintainers, we agreed that this just looks like some of the annoying bits of interacting with Vimscript, and not really a bug in the omnifunc implementation.

I've published the workaround PR again :)

**Comment by MariaSolOs** [comment]
@uga-rosa I'm unfortunately still experiencing this issue :/
![image](https://github.com/uga-rosa/ccc.nvim/assets/62502207/88f01260-b0e1-4011-83f2-1ec03fa98fde)
