### ISSUE TITLE
method textDocument/documentColor is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by RAprogramm** [uga-rosa/ccc.nvim#104]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

On BufEnter all is ok, colors shows correctly, but when i enter "INSERT" mode i get this err `method textDocument/documentColor is not supported by any of the servers registered for the current buffer`

### Environments

`neovim v0.10.0-dev-2457`
`Linux Arch 6.7.6`

### Minimal reproducible full config

options.lua
```lua
-- FIX: rgb bars always grey

return function()
  return {
    -- win_opts = {
    -- relative = 'cursor',
    -- row = 1,
    -- col = 1,
    -- style = 'minimal',
    -- border = 'single',
    -- },
    highlighter = {
      auto_enable = true,
      excludes = { 'neo-tree' },
      -- lsp = true,
    },
  }
end

```

install in lazy
```lua
  {
    'uga-rosa/ccc.nvim',
    event = { 'BufRead', 'BufNewFile' },
    -- cmd = {
    --   'CccHighlighterToggle',
    --   'CccPick',
    --   'CccConvert',
    -- },
    opts = require('plugins.ccc.options'),
  },
```

But this happens when i enter to buf without lsp server (for css in my case)

when i enter to buf which have lsp server support (lua for example) there is no errors, but
not correct RGB bars

![240228_15h00m02s_screenshot](https://github.com/uga-rosa/ccc.nvim/assets/70325462/976ff7ea-c935-4e0b-aeb4-7497200847f0)

**Comment by iafshinafshin** [comment]
Hey  , I created a issues but he doesn't followed up

**Comment by fbosch** [comment]
I have this issue as well

**Comment by iafshinafshin** [comment]
> **_Hey , I created a issue(#103) but he doesn't followed up_**

**Comment by ccwanggl** [comment]
I have this issue as well, I am on the windows 11 with terminal app.

**Comment by uga-rosa** [comment]
Do you have `'termguicolors'` enabled?
I can't do anything about the lsp error because I can't reproduce it here. Please provide a minimum init.lua and reproduction procedure that can reproduce the issue on its own, as written in the template.

**Comment by uga-rosa** [comment]
The problem with the bar highlight disappearing has been fixed, and I'd like to look into the LSP error and whatnot, but this issue is confusing, so please start a new one.

**Comment by Darukutsu** [comment]
In my config error is somehow related to `null-ls/none-ls` & `mason-null-ls handler`.

In mean time you can do.
```
vim.notify = function(msg, log_level, opts)
  if string.match(msg, "method textDocument/documentColor is not supported by any of the servers registered for the current buffer") then
    -- Do nothing to suppress the warning
  else
    -- Call the original vim.notify function for other messages
    vim.notify(msg, log_level, opts)
  end
end
```

**Comment by uga-rosa** [comment]
I tried to handle the lsp error. Try the latest version to see if it's fixed.

**Comment by iafshinafshin** [comment]
Hello, sometimes it works and sometimes doesn't works

**Comment by uga-rosa** [comment]
If you really want me to fix it, make an issue that follows the template and has a proper minimum init.lua and procedure to reproduce it. Again, I've never seen that error, so I can only guess.

**Comment by iafshinafshin** [comment]
Hey, I now removed all configs and I use packer installer and  rebuilt all of them and it's working
