### ISSUE TITLE
CccPick not working correctly

### ISSUE THREAD

**Issue by Jlchong3** [uga-rosa/ccc.nvim#106]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

CccPick stop showing the colors in the pickers after moving them first

### Environments

Windows 11

NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320

### Minimal reproducible full config

No additional config

### Steps to reproduce

Run command CccPick and try to modify color

### Expected behavior

Bars changing color depending on the amount of each one

### Actual behavior

It all turns gray after I try to modify the colors

### Additional context

How it shows up at the begging (It works normally)
![image](https://github.com/uga-rosa/ccc.nvim/assets/127264125/adb4d5f4-18c7-498b-9bb8-e08d93a91db3)

How it show after I start modifying
![image](https://github.com/uga-rosa/ccc.nvim/assets/127264125/da8b66e8-b52b-4283-86b7-ad220fa2b967)

**Comment by uga-rosa** [comment]
Please write Minimal reproducible full config properly. I can't reproduce it.

![issue106](https://github.com/uga-rosa/ccc.nvim/assets/82267684/7fa349d3-bb1b-4436-bea0-1894c80cb7cc)

**Comment by Jlchong3** [comment]
## Minimal Reproducible config
```lua
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        'git',
        'clone',
        '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git',
        '--branch=stable', -- latest stable release
        lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({

	{
		'folke/tokyonight.nvim',
		config = function()
			vim.cmd.colorscheme 'tokyonight'
		end,

	},

    {
        'uga-rosa/ccc.nvim',
        opts = {
            highlighter = {
                auto_enable = true,
 
            },
        }
    },

},{})
```
For this config I am using Windows WSL Ubuntu, and I added a different colorscheme in case that was a problem, but the problem still persists.

I also tried the plugin with the previous version 1.7.2 and it worked correctly

**Comment by uga-rosa** [comment]
OK, I understand. This is a bug that does not happen in nightly, but only in 0.9.5. I will try to fix it now that it is confirmed.

**Comment by RAprogramm** [comment]
i have reverse situation .
when i pick the color bars are white, and when i start to modify colors (left or right move) all is ok....
