### ISSUE TITLE
Error display highlighting

### ISSUE THREAD

**Issue by kola-web** [uga-rosa/ccc.nvim#107]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

https://github.com/uga-rosa/ccc.nvim/assets/46446884/1fbde25f-1990-46ad-9dcd-41d81645d969

### Environments

![image](https://github.com/uga-rosa/ccc.nvim/assets/46446884/5b9d0885-7126-4133-8d25-c5fb9cdaf457)
![image](https://github.com/uga-rosa/ccc.nvim/assets/46446884/29398b80-fb04-4635-8f74-c92b8ac60e4f)

### Minimal reproducible full config

```lua

set termguicolors

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/autoload/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'uga-rosa/ccc.nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

lua <<EOF
local ccc = require("ccc")
local mapping = ccc.mapping

ccc.setup({
    highlighter = {
      auto_enable = false,
      lsp = false,
    },
})

require("lspconfig").cssls.setup({})
EOF
```

### Steps to reproduce

Refer to the video above

### Expected behavior

Can be displayed normally

### Actual behavior

Error display highlighter

### Additional context

none

**Comment by uga-rosa** [comment]
I just fixed it, have you tried the latest version?

**Comment by kola-web** [comment]
Not yet, I'll try it now

**Comment by uga-rosa** [comment]
Hmmm? I think it was fixed in the update I just did. Are you sure it is the latest version? I can't reproduce it.

![issue107](https://github.com/uga-rosa/ccc.nvim/assets/82267684/26e277bf-0170-443a-80e4-d7787177d9c4)

**Comment by kola-web** [comment]
OK, I'll try again

**Comment by kola-web** [comment]
@uga-rosa Hello, I found an interesting problem. When the file has only a dozen lines, there is no problem, but when the file reaches about 700 lines, problems will occur.

**Comment by uga-rosa** [comment]
I can't reproduce ...
![issue106](https://github.com/uga-rosa/ccc.nvim/assets/82267684/b9c02f4e-9536-4882-bc71-642d9f8148bc)

**Comment by kola-web** [comment]
Thank you for your support. I will close this issue first. It is possible that this issue is caused by my own configuration.

**Comment by uga-rosa** [comment]
If you find the cause, please put it up again. I'd like to fix bugs that can be fixed :)

**Comment by kola-web** [comment]
Thank you for your hard work
