### ISSUE TITLE
Green not displaying green

### ISSUE THREAD

**Issue by Jlchong3** [uga-rosa/ccc.nvim#109]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

When I use the word green in my css file, it displays a tone of orange

### Environments

Windows 11
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320

### Minimal reproducible full config

  return{
  {
        'uga-rosa/ccc.nvim',
        event = 'VeryLazy',
        opts = {
            highlighter = { auto_enable = true, lsp = true },
        },
   },
}

### Steps to reproduce

Go to a css file and type green as color property

### Expected behavior

background of the word becomes green

### Actual behavior

the background becomes orange

### Additional context

Here is a photo of the problem
![image](https://github.com/uga-rosa/ccc.nvim/assets/127264125/f2b8a9dd-3871-4157-9a79-e660f37008d6)

**Comment by uga-rosa** [comment]
This is not a full config.

> If there are deficiencies here, the issue will not be respond. Please understand that this is the most important section.
You must provide a working config based on [this](https://github.com/uga-rosa/ccc.nvim/blob/main/utils/minimal.vim). Not part of config.
Users of packer.nvim should check to see if there any plugins left in ~/.local/share/nvim/site/pack/packer.
> 1. Copy the base minimal config to the ~/ccc-repro.vim.
> 2. Edit ~/ccc-repro.vim for reproducing the issue.
> 3. Open nvim -u ~/ccc-repro.vim.
> 4. Check steps to reproduce.

**Comment by Jlchong3** [comment]
```lua 
vim.o.termiguicolors = true

local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        'git',
        'clone',
        '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git',
        '--branch=stable', -- latest stable release
      lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
   {
    'uga-rosa/ccc.nvim',
        opts = {
            highlighter = { auto_enable = true},
        },
   },

       {
        'catppuccin/nvim',
        name = 'catppuccin',
        priority = 1000,
	config = function() 
		vim.cmd.colorscheme 'catppuccin'
	end,
   },

   {
        'neovim/nvim-lspconfig',
        dependencies = {
            'williamboman/mason.nvim',
            'williamboman/mason-lspconfig.nvim',
	}
   },

},{})

require('mason').setup()
require('mason-lspconfig').setup()

local mason_lspconfig = require('mason-lspconfig')

local servers = {
    cssls = {
        filetypes = {'css'}
    }
}

mason_lspconfig.setup {
    ensure_installed = {'cssls'}
}

-- Set up language servers
for server_name, config in pairs(servers) do
    mason_lspconfig.setup_handlers {
        function(name)
            if name == server_name then
                require('lspconfig')[name].setup {
                    filetypes = config.filetypes
                }
            end
        end
    }
end

```

This is the minimal config, and I still have the same problem in windows and in the WSL

![image](https://github.com/uga-rosa/ccc.nvim/assets/127264125/374b6671-4034-49bb-8c6d-693b732d111c)

Using the previous version 1.7.0 works as expected btw

**Comment by uga-rosa** [comment]
You'll need the css files too.
Also, is this color scheme really necessary for reproduction?

**Comment by Jlchong3** [comment]
I am going to be honest I don't know why you are so fixiated with this reproduction procedure, I am just trying to point out something that is not working. The previous comment doesn't have anything more than your plugin, a colorscheme,  and a Lsp setup, but well since you want it without the colorscheme.

```lua
vim.o.termguicolors = true

local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        'git',
        'clone',
        '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git',
        '--branch=stable', -- latest stable release
      lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
   {
    'uga-rosa/ccc.nvim',
        opts = {
            highlighter = { auto_enable = true},
        },
   },

   {
        'neovim/nvim-lspconfig',
        dependencies = {
            'williamboman/mason.nvim',
            'williamboman/mason-lspconfig.nvim',
	}
   },

},{})

require('mason').setup()
require('mason-lspconfig').setup()

local mason_lspconfig = require('mason-lspconfig')

local servers = {
    cssls = {
        filetypes = {'css'}
    }
}

mason_lspconfig.setup {
    ensure_installed = {'cssls'}
}

-- Set up language servers
for server_name, config in pairs(servers) do
    mason_lspconfig.setup_handlers {
        function(name)
            if name == server_name then
                require('lspconfig')[name].setup {
                    filetypes = config.filetypes
                }
            end
        end
    }
end

```

The css file is just any css file, I'm going to make one on the same directory as the config.

![image](https://github.com/uga-rosa/ccc.nvim/assets/127264125/45ffc215-a436-4878-8a0c-1c1fe3e77698)

And then same result as the previous ones, except that fooling around I found out blue also has a problem.

![image](https://github.com/uga-rosa/ccc.nvim/assets/127264125/247fd2cd-eefb-4b9b-b02e-87399c26fc3f)

**Comment by uga-rosa** [comment]
This is because this issue was not reproduced at hand. I can't fix a bug I can't confirm.
I'm still not sure what the cause is, but I found that I can reproduce this bug after formatting, even though it is not highlighted right after startup. Now I can finally investigate.
