### ISSUE TITLE
[Feature] HSV support

### ISSUE THREAD

**Issue by sindrets** [uga-rosa/ccc.nvim#11]
Really interesting plugin, great work!

---

I frequently tend to prefer HSV over HSL when tweaking colors, as - opposed to the Lightness component in HSL - the Value component of HSV better preserves chroma. Would you be willing to support the HSV color model in your plugin?

![HSL-v-HSV](https://user-images.githubusercontent.com/2786478/190866205-3c5911ae-dbdb-47f3-a404-e1950bca9357.jpg)

<sup>Image source: <a href="https://en.m.wikipedia.org/wiki/HSL_and_HSV">Wikipedia - HSL and HSV</a></sup>

**Comment by sindrets** [comment]
For reference, [I have an HSV lua implementation in my dotfiles](https://github.com/sindrets/dotfiles/blob/5ce0353a137e05ed2dc8e10e7ca5bfff2633393d/.config/nvim/lua/user/common/color.lua) that also includes conversion between HSL and HSV.

**Comment by uga-rosa** [comment]
Done in a89d4c32cc934727aed9609f50b7e6bc1e5a29d7

**Comment by uga-rosa** [comment]
Note: I adopt the cylinder model of HSL/HSV.

**Comment by sindrets** [comment]
Brilliant, thanks!

> Note: I adopt the cylinder model of HSL/HSV.

It's the same model. The cone diagram here represents the plot of hue and lightness against chroma for HSL, and the plot of hue and value against chroma for HSV. The representation shows the difference in how the included components affect chroma for the two models.

**Comment by uga-rosa** [comment]
Hmm? I'm not very familiar with it, but aren't there two models for HSL/HSV, (bi)cone and cylinder, with different calculation methods?
