### ISSUE TITLE
ccc.nvim highlights lch colour on top of oklch color in css

### ISSUE THREAD

**Issue by johannesrld** [uga-rosa/ccc.nvim#110]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

this seems to have been broken in the [refactor commit](https://github.com/uga-rosa/ccc.nvim/commit/36c25effa467213b27052f793c3c9c7e6aea5de5) as the commit before it works completely fine and highlights oklch declarations completely fine:

the commit just before the refactor (`392ef0640b96684e88b3965f32f3bc42530f66c3`):

![image](https://github.com/uga-rosa/ccc.nvim/assets/71744831/e3e588db-bea9-4c65-82ba-08d34619f6d5)

the refactor commit (`36c25effa467213b27052f793c3c9c7e6aea5de5`):

![image](https://github.com/uga-rosa/ccc.nvim/assets/71744831/1f5686a6-a8e4-4aa7-81a1-83f1c02ca460)

### Environments

im running this on WSL openSUSE tumbleweed, neovim version info is:
```
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Compilation: /usr/bin/cc  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-5_1-2.1 -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/include -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/cmake.config -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Minimal reproducible full config

```vim
set termguicolors

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/autoload/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
"=================IMPORTANT!!!========================
"NOTE: after installing (and whilst switching between these two commits)
"you have `rm -rf /tmp/plugged` otherwise you wont switch between them properly if at all
"=================IMPORTANT!!!========================
" Plug 'uga-rosa/ccc.nvim', { 'commit': '392ef0640b96684e88b3965f32f3bc42530f66c3' } "This is the last commit that had oklch highlighting working
Plug 'uga-rosa/ccc.nvim', { 'commit': '36c25effa467213b27052f793c3c9c7e6aea5de5' } "This is the commit that introduced the issue
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

lua <<EOF
local ccc = require("ccc")
local mapping = ccc.mapping

ccc.setup({
    -- Minimal configurations required to reproduce the problem.
    highlighter = {
      auto_enable = true,
    }
})

require("lspconfig").cssls.setup({})
EOF

```

### Steps to reproduce

1. Launch the neovim with the minimal config enabled
2. Navigate to a css file that contains some oklch declaration, for example:
```css
main {
  color: oklch(77.08% 0.102 12.84);
}
```
4. you will see that highlighting is broken.

### Expected behavior

highlighting `oklch` colours should work as they did before `36c25effa467213b27052f793c3c9c7e6aea5de5`, there should be only one colourspace highlighted on the variable

### Actual behavior

lch colours are highlighted on top of oklch colours

### Additional context

I'm not sure if this is an issue for other colourspaces too, e.g. highlighting `lab` colours on top of `oklab` colours etc etc

**Comment by uga-rosa** [comment]
Ok, I reproduced it.

**Comment by uga-rosa** [comment]
Correction. Please confirm.
