### ISSUE TITLE
Error when using okhsl color input mode

### ISSUE THREAD

**Issue by JulesNP** [uga-rosa/ccc.nvim#111]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

Launching the color picker seems to cause an error when using input mode okhsl, if the color is set to the default, or `#000000`.

### Environments

Neovim 0.9.5

### Minimal reproducible full config

```vim
set termguicolors

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/autoload/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'uga-rosa/ccc.nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

lua <<EOF
local ccc = require("ccc")
local mapping = ccc.mapping

ccc.setup({
  -- Minimal configurations required to reproduce the problem.
  inputs = {
    ccc.input.okhsl,
  }
})

require("lspconfig").cssls.setup({})
EOF
```

### Steps to reproduce

Run `:CccPick` when not hovering over any color, or when hovering over color `#000000`.

### Expected behavior

Color picker appears.

### Actual behavior

The following error message is displayed:
```
Error executing Lua callback: /tmp/plugged/vim-plug/ccc.nvim/lua/ccc/utils/api.lua:44: Invalid highlight color: '#800000000000000080000000000000008000000000000000'
stack traceback:
        [C]: in function 'nvim_set_hl'
        /tmp/plugged/vim-plug/ccc.nvim/lua/ccc/utils/api.lua:44: in function 'set_hl'
        /tmp/plugged/vim-plug/ccc.nvim/lua/ccc/ui/float.lua:260: in function 'highlight'
        /tmp/plugged/vim-plug/ccc.nvim/lua/ccc/ui/float.lua:33: in function 'open'
        /tmp/plugged/vim-plug/ccc.nvim/lua/ccc/core.lua:65: in function 'pick'
        /tmp/plugged/vim-plug/ccc.nvim/lua/ccc/init.lua:26: in function </tmp/plugged/vim-plug/ccc.nvim/lua/ccc/init.lua:25>
```

**Comment by uga-rosa** [comment]
Correction.
If you have hsl as your default input,, it is recommended to set default_color (`:h ccc-option-default-color`).
