### ISSUE TITLE
Do not call `textDocument/documentColor` when LSP server doesn't support it

### ISSUE THREAD

**Issue by simonmandlik** [uga-rosa/ccc.nvim#117]
### Request for other features

Some LSP servers do not support `textDocument/documentColor`. This leads to warnings, and, in worse cases, crashes.

For example, LS for julia crashes when receiving a request for `textDocument/documentColor`.

Would it be possible to not generate these requests when the LSP does not support it? This can be deduced from server capabilities, i.e.

```lua
vim.lsp.get_clients()[1].server_capabilities
```

For example, julia LS declares [here](https://github.com/julia-vscode/LanguageServer.jl/blob/1cc14a9eceda14802d929de5eb0cd448aa3f3279/src/requests/init.jl#L25) that it doesn't support `textDocument/documentColor`.

Thanks!

**Comment by uga-rosa** [comment]
Thanks for the report. I know how to do the checks, and I'm doing some of them. It's just that doing something like Promise.all in lua is a bit of a pain, so I've been putting off dealing with it strictly. Most servers don't crash when they are asked to use unsupported methods.
Well, now that you've reported it, we'll deal with it. Please wait a while.

**Comment by uga-rosa** [comment]
@simonmandlik 
Please test `fix/117` branch

**Comment by lcw** [comment]
I just test `fix/117` and it didn't work for me.

**Comment by uga-rosa** [comment]
@lcw 
What does “it didn't work for me.” mean? Do you still get the same warnings and LS crashes (the issue is not resolved), or does the highlighting with LS itself no longer work?

**Comment by lcw** [comment]
Good questions.  When I updated ccc to the branch with the proposed fix `9dd83ea` I still see LS for julia crashing when receiving a request for `textDocument/documentColor`.

My Lazy config for loading ccc is:

```lua
  {
    'uga-rosa/ccc.nvim',
    branch = 'fix/117',
    config = function()
      local ColorInput = require 'ccc.input'
      local convert = require 'ccc.utils.convert'

      local RgbHslCmykInput = setmetatable({
        name = 'RGB/HSL/CMYK',
        max = { 1, 1, 1, 360, 1, 1, 1, 1, 1, 1 },
        min = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        delta = { 1 / 255, 1 / 255, 1 / 255, 1, 0.01, 0.01, 0.005, 0.005, 0.005, 0.005 },
        bar_name = { 'R', 'G', 'B', 'H', 'S', 'L', 'C', 'M', 'Y', 'K' },
      }, { __index = ColorInput })

      function RgbHslCmykInput.format(n, i)
        if i <= 3 then
          -- RGB
          n = n * 255
        elseif i == 5 or i == 6 then
          -- S or L of HSL
          n = n * 100
        elseif i >= 7 then
          -- CMYK
          return ('%5.1f%%'):format(math.floor(n * 200) / 2)
        end
        return ('%6d'):format(n)
      end

      function RgbHslCmykInput.from_rgb(RGB)
        local HSL = convert.rgb2hsl(RGB)
        local CMYK = convert.rgb2cmyk(RGB)
        local R, G, B = unpack(RGB)
        local H, S, L = unpack(HSL)
        local C, M, Y, K = unpack(CMYK)
        return { R, G, B, H, S, L, C, M, Y, K }
      end

      function RgbHslCmykInput.to_rgb(value)
        return { value[1], value[2], value[3] }
      end

      function RgbHslCmykInput:_set_rgb(RGB)
        self.value[1] = RGB[1]
        self.value[2] = RGB[2]
        self.value[3] = RGB[3]
      end

      function RgbHslCmykInput:_set_hsl(HSL)
        self.value[4] = HSL[1]
        self.value[5] = HSL[2]
        self.value[6] = HSL[3]
      end

      function RgbHslCmykInput:_set_cmyk(CMYK)
        self.value[7] = CMYK[1]
        self.value[8] = CMYK[2]
        self.value[9] = CMYK[3]
        self.value[10] = CMYK[4]
      end

      function RgbHslCmykInput:callback(index, new_value)
        self.value[index] = new_value
        local v = self.value
        if index <= 3 then
          local RGB = { v[1], v[2], v[3] }
          local HSL = convert.rgb2hsl(RGB)
          local CMYK = convert.rgb2cmyk(RGB)
          self:_set_hsl(HSL)
          self:_set_cmyk(CMYK)
        elseif index <= 6 then
          local HSL = { v[4], v[5], v[6] }
          local RGB = convert.hsl2rgb(HSL)
          local CMYK = convert.rgb2cmyk(RGB)
          self:_set_rgb(RGB)
          self:_set_cmyk(CMYK)
        else
          local CMYK = { v[7], v[8], v[9], v[10] }
          local RGB = convert.cmyk2rgb(CMYK)
          local HSL = convert.rgb2hsl(RGB)
          self:_set_rgb(RGB)
          self:_set_hsl(HSL)
        end
      end

      local ccc = require 'ccc'
      ccc.setup {
        inputs = {
          RgbHslCmykInput,
        },
        -- highlighter = {
        --   auto_enable = false,
        --   lsp = false,
        -- },
      }
    end,
  },
```

Interestingly, I just tried the following config:
```lua
 {
    'uga-rosa/ccc.nvim',
    branch = 'fix/117',
 },
```
and I don't see any LS crashes.  I don't know if the highlighing is still working.  I just use ccc for the color picker.

**Comment by uga-rosa** [comment]
I can't try julia lsp because it won't start...
Is there a polite way to set up julia lsp or an example of how to reproduce this on another lsp?

**Comment by simonmandlik** [comment]
Have you seen [this](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#julials)?

**Comment by MariaSolOs** [comment]
It seems like this is also causing issues with pickers like `fzf-lua`. See this issue for example: https://github.com/ibhagwan/fzf-lua/issues/1294

**Comment by uga-rosa** [comment]
I have not been able to reproduce this issue at hand, so it is difficult to fix.
The julials will not start. If you want me to fix it, please provide a setup and instructions that I can properly reproduce using other ls.

**Comment by MariaSolOs** [comment]
@uga-rosa I think that #118 should fix this issue. From the previous comments in this thread it seems like @lcw's problems are being caused by different issues in their configuration.

**Comment by uga-rosa** [comment]
@MariaSolOs 
Ok, I merged the PR and close this issue.

@lcw
I would be happy to sort out the situation and prepare another issue.
