### ISSUE TITLE
FR: Option to not highlight short hex codes like `#123`

### ISSUE THREAD

**Issue by chrisgrieser** [uga-rosa/ccc.nvim#119]
### Request for other features

There are various strings like `#123` for referencing GitHub issues, which also get highlighted by ccc. An option to disable highlighting short hex codes would be useful for this, but looking through the readme, there is no such option. 

Related issue #76 was closed without resolution (and there does not seem to be a follow-up in the discussion), the option `exclude_pattern` mentioned in linked issues was apparently removed in https://github.com/uga-rosa/ccc.nvim/commit/698ba07e3e6079647158c310f6890040056c6cbf, thus there does not seem to be any option or method to achieve this on the user's end.

**Comment by uga-rosa** [comment]
#77 couldn't help you?

**Comment by uga-rosa** [comment]
If this is a common request, and we are talking about 77 solutions being too cumbersome, a solution might be to split picker.hex into picker.hex_long and picker.hex_short. Let me know your opinion.

**Comment by chrisgrieser** [comment]
> #77 couldn't help you?

Ah, I missed that one, because the discussion was closed and is thus not initially shown when going to the `Discussions` tab. (kinda annoying design choice by GitHub…) Yeah, the suggestion there works, I added this to before the setup call:
```lua
ccc.picker.hex.pattern = { [=[\v%(^|[^[:keyword:]])\zs#(\x\x)(\x\x)(\x\x)>]=] }
```

> If this is a common request, and we are talking about 77 solutions being too cumbersome, perhaps we should add an option for easier setup.

Well, since it's only a one-liner, it's not too cumbersome. Nonetheless, I think a that having strings like `#123` referring to github references is very common, so that it is worth it to make a simple option out of it. Even though it may be a picker in ccc's internal logic, from a user perspective, I'd find it more intuitive if it is a sub-key of `highlighter`, for example:

```lua
local ccc = require'ccc'
ccc.setup {
  highlighter = {
    highlight_short_hex_keys = true;
  }
}
```

**Comment by uga-rosa** [comment]
> Well, since it's only a one-liner, it's not too cumbersome. Nonetheless, I think a that having strings like #123 referring to github references is very common, so that it is worth it to make a simple option out of it. Even though it may be a picker in ccc's internal logic, from a user perspective, I'd find it more intuitive if it is a sub-key of highlighter, for example:
> ```lua
> local ccc = require'ccc'
> ccc.setup {
>   highlighter = {
>     highlight_short_hex_keys = true;
>   }
> }
> ```
I would like the design to be closed to only editing the picker, the way to control the colors that can be highlighted/picked. So I'm not sure I can accept that suggestion.
