### ISSUE TITLE
Check for server capabilities before sending textDocument/documentHighlight

### ISSUE THREAD

**Issue by MariaSolOs** [uga-rosa/ccc.nvim#125]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

This is a followup issue of #117. Despite the fix in #118, the same capability check should be done for other LSP requests.

### Environments

Fedora Linux, Neovim version v0.11.0-dev-302+gbe999e6a0.

### Expected behavior

For `ccc` to not conflict with other plugins.

### Actual behavior

The following error appears when using the files picker from `fzf-lua`:
![image](https://github.com/uga-rosa/ccc.nvim/assets/62502207/c231540d-bc39-4be1-8ef1-ed8c39b97c98)

**Comment by uga-rosa** [comment]
I'm not calling textDocument/documentHighlight. Can you give me more info?
I've grep'd it and the library has one place that calls that method, but the main body doesn't call this. I'm only using this library in some tests, so it shouldn't affect the user.

**Comment by MariaSolOs** [comment]
Hmm that's strange. I also grep'd my plugins and this is the only plugin I have that has a reference to that method...

**Comment by uga-rosa** [comment]
Please add "Minimal reproducible full config". You may include lsp and other plugins (that may be relevant), but please make it one init.lua.

**Comment by MariaSolOs** [comment]
I apologize. After investigating this further, this seems like an issue with an autocommand I defined and not this plugin.

Sorry about that!

**Comment by uga-rosa** [comment]
I'm glad you got it resolved.
