### ISSUE TITLE
using mapping.reset_mode does nothing

### ISSUE THREAD

**Issue by SadBoiLlama** [uga-rosa/ccc.nvim#128]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

default binding r does nothing when pressed
u = require'ccc'.mapping.reset_mode does nothing when pressed

idk much lua or nvim plugins so i could be talking out my ass but theres nothing about reset_mode in the mapping file. did it just get missed some how?

### Environments

arch - ¯\_(ツ)_/¯
neovim - 0.10.1

### Minimal reproducible full config

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

if not (vim.uv or vim.loop).fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	"uga-rosa/ccc.nvim",
	config = function()
		require("ccc").setup({
			highlighter = {
				auto_enable = true,
				lsp = true,
			},
			mappings = {
				r = require("ccc").mapping.fuck,
			},
		})
	end,
})
```

### Steps to reproduce

press r after changing value

### Expected behavior

reset to state window was opened as

### Actual behavior

get told modifiable is off

**Comment by uga-rosa** [comment]
Thanks for your report. The action was indeed gone.
Fixed.
