### ISSUE TITLE
[Feature request] Highlight the color that ccc.nvim can pick.

### ISSUE THREAD

**Issue by roland-rollo** [uga-rosa/ccc.nvim#14]
Hi,

I was wondering if I can replace `colorizer.lua` with using only `ccc.nvim`. If I open some files and there are, like hex numbers meaning come colors it would show, what color it's. I mean something like this:
![ps_20220629004516](https://user-images.githubusercontent.com/44477799/176316978-906b133f-8186-4a10-aa9d-d315943e788d.png)

**Comment by uga-rosa** [comment]
In fact, this is the next feature I was planning to inplement ;)

**Comment by uga-rosa** [comment]
Done.

**Comment by roland-rollo** [comment]
Thanks! That was quick and exacting. Just added to my config:
```lua
local ccc = require("ccc")
local mapping = ccc.mapping
ccc.setup({
    highlighter = {
      auto_enable = true,
          },
})
```

But I have one question. Is there an option not to color the parts of the words that mean the colors?
![ps_20220919190945](https://user-images.githubusercontent.com/44477799/191074464-ba372ab0-ce4e-40a5-a253-44576642985b.png)

**Comment by uga-rosa** [comment]
This highlighting is registered in ccc-option-pickers and highlights the colors that can be picked up. So, you can do it this way.
```lua
local ccc = require("ccc")
ccc.setup({
    pickers = {
        ccc.picker.hex,
        ccc.picker.css_rgb,
        ccc.picker.css_hsl,
        -- ccc.picker.css_name,
    },
}
```

**Comment by uga-rosa** [comment]
You can also specify file types to enable highlighting by using the options `highlight.filetypes` and `highlight.excludes`.

**Comment by roland-rollo** [comment]
Thanks! <3

**Comment by uga-rosa** [comment]
I have already decided to disable css_name by default.

**Comment by SirCharlieMars** [comment]
<img width="1512" alt="CleanShot 2022-09-21 at 13 07 05@2x" src="https://user-images.githubusercontent.com/31679231/191578691-551949df-a381-4af4-b4c1-351c517261a8.png">
This is probably an issue but css_name also highlights words that contain a css_name. Probably a regular expression thing?

**Comment by uga-rosa** [comment]
Have you updated to the latest version?

**Comment by gegoune** [comment]
Hey @uga-rosa, not sure if I should open new issue, but with latest version and config such as

```lua
require('ccc').setup {
  highlighter = {
    auto_enable = true,
  },
}
```

I am not getting any highlights. Also tried running `CccHighlighterEnable` but still nothing.

**Comment by uga-rosa** [comment]
https://github.com/uga-rosa/ccc.nvim/blob/3b4ae50e7f656e6c1543bee2ce4ef5a802866479/lua/ccc/config/default.lua#L30-L34
This is the default setting, but I don't have css_name in there properly. And I can't reproduce it in my environment. Are you sure you are able to update it? Can you go to the plugin directory and check the commit?

**Comment by SirCharlieMars** [comment]
> Have you updated to the latest version?

I have updated it to the latest version, and I have enabled css_name, but it still highlights words that don't match exactly.

**Comment by SirCharlieMars** [comment]
<img width="1511" alt="CleanShot 2022-09-21 at 15 50 05@2x" src="https://user-images.githubusercontent.com/31679231/191607670-8c4f64b4-33eb-4764-abc7-caec1275556a.png">

**Comment by uga-rosa** [comment]
Ah - you're enabling it yourself.
It's an exact match. ccc just haven't looked at the before and after of it. And there is an option called exclude_pattern that I put in to counteract that, but it's hard to use as it is now, so I'll let you know when I update it, along with how to set it up.

**Comment by uga-rosa** [comment]
Done.
With `exclude_pattern`, you can determine the conditions before and after the match. The default settings are as follows
```lua
exclude_pattern = {
    hex = "[%w_]{{pattern}}",
    css_rgb = nil,
    css_hsl = nil,
    css_name = {
        "[%w_]{{pattern}}",
        "{{pattern}}[%w_]",
    },
}
```
With this setting, css_name is now excluded if there is an alphabet or underscore before or after this.

**Comment by SirCharlieMars** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/31679231/191617255-ce269485-5a31-423a-b92c-11f92caac12b.png">
I get this error once I update to the latest commit

**Comment by uga-rosa** [comment]
Sorry, fixed.

**Comment by roland-rollo** [comment]
Wow, guys! For names it now works ideally. :D That's so cool. <3

**Comment by SirCharlieMars** [comment]
Yep! Thank you so much!
