### ISSUE TITLE
[BUG]: Unable to refocus on color picker if switching application focus with picker open

### ISSUE THREAD

**Issue by eccentric-j** [uga-rosa/ccc.nvim#16]
## Reproduction

1. Install ccc
2. Run `:CccPick`
3. With the picker open, switch focus to another application like browser
4. Click the CccPick window to try and restore focus

## Expected

Ideally the bindings should continue to work, or the picker closes

## Actual

Picker stays open and cannot be closed or reactivated

Despite that this plugin is awesome! ❤️

**Comment by uga-rosa** [comment]
Hmmm, it doesn't seem to reproduce. What OS and terminal are you using? Also, what is your mapping for cursor clicks?
![issue16](https://user-images.githubusercontent.com/82267684/191094276-ee7e6edb-e01f-400c-b381-5d42fb5d0275.gif)

**Comment by uga-rosa** [comment]
Ah, perhaps you are moving the neovim window by clicking. Can't you use `<C-w><C-w>` to get back to the UI?

**Comment by eccentric-j** [comment]
I'm using neovim via neovide on latest OS X.

Have not configured any mouse specific settings yet.

**Comment by eccentric-j** [comment]
`<C-w><C-w>` does get back to the UI!

![2022-09-19 16 15 01](https://user-images.githubusercontent.com/590297/191108416-1d854550-def4-4890-ac13-de0afee419ca.gif)
