### ISSUE TITLE
How to make the slider look smoother? It seems more blocky than README.

### ISSUE THREAD

**Issue by eccentric-j** [uga-rosa/ccc.nvim#17]
![image](https://user-images.githubusercontent.com/590297/191089223-a56a1163-9ba4-4d9e-b730-cee30bfc3112.png)

When using the picker, noticed my sliders are a bit more blocky than seen in the readme screenshot. Any hints on what settings would affect that so I can make it look smoother?

**Comment by uga-rosa** [comment]
Font influence. The following settings allow you to set the character used for the slider.
```lua
require("ccc").setup({
    bar_char = ""
})
```

**Comment by eccentric-j** [comment]
Thank you!

**Comment by eccentric-j** [comment]
Found myself getting best results so far with:

```fennel
(ccc.setup {:bar_char "█"})
```

![image](https://user-images.githubusercontent.com/590297/191110081-459483e4-fc84-4bb4-bef1-fd7efc61b583.png)
