### ISSUE TITLE
Normal float colour is altered in floating windows

### ISSUE THREAD

**Issue by akinsho** [uga-rosa/ccc.nvim#19]
Hi 👋🏿,

Just been trying this plugin out as an alternative to `colorizer` and it seems really cool so far. One strange issue I've noticed though is that the colour of my lsp floating window and of `CccNormalFloat` itself are different from what I set as my `NormalFloat` e.g.

With ccc.nvim installed, notice the border is dark, but the background of the text is not.
<img width="937" alt="image" src="https://user-images.githubusercontent.com/22454918/191694800-56defd7d-de42-4f6c-b932-6ac011a571e4.png">
My normal float colour however is unchanged.

Without ccc.nvim I get which is expected.
<img width="937" alt="image" src="https://user-images.githubusercontent.com/22454918/191695218-a520b325-39fd-4a31-88dc-947b34ea8a2b.png">

The `CccPick` window itself also seems to ignore my settings for `NormalFloat` and even setting `CccFloatNormal` makes no difference
<img width="464" alt="image" src="https://user-images.githubusercontent.com/22454918/191695466-f15375c0-6a24-41ba-835d-42bcfe6dccf0.png">

I'm not sure how highlights are being applied, e.g. using namespaces, but it seems to be leaking into other areas somehow.

My ccc config is:
```lua
use({
      'uga-rosa/ccc.nvim',
      config = function()
        local ccc = require('ccc')
        ccc.setup({
          pickers = {
            ccc.picker.hex,
            ccc.picker.css_rgb,
            ccc.picker.css_hsl,
          },
          win_opts = { border = as.style.current.border }, -- var representing some custom border chars
          highlighter = {
            auto_enable = true,
            excludes = { 'dart' },
          },
        })
      end,
    })
```

**Comment by akinsho** [comment]
Ahh so I've managed to narrow this down a little to delaying loading this plugin using `event = BufRead` I noticed a similar issue with window highlight namespaces using `tint.nvim` I think there is a race condition of needing to wait for colorschemes before using window highlights. But delaying the loading to `BufRead` means that when I enter a file the auto highlighting does not work till I manually run `CccHighlightToggle`

**Comment by uga-rosa** [comment]
How about this?

**Comment by uga-rosa** [comment]
Also, that pickers is now the default value, so you don't need to set it.

**Comment by akinsho** [comment]
It still behaves the same as far as I can see, i.e. it's highlighting is changing the highlights of my LSP hover window, and it still doesn't match the value I set for float normal.

Regarding the pickers, I only set them, so I could take out the ccs name picker since it was matching colours inside normal words liked `{ Greenfield = true }` green would be getting highlighted so I just wanted to turn that off.

**Comment by uga-rosa** [comment]
It is not a issue with this plugin that `NormalFloat` does not reflected. Use `CccFloatNormal` and `CccFloatBorder`.
I've already fixed that in the picker, see `:h ccc-option-exclude-pattern`.

**Comment by akinsho** [comment]
@uga-rosa 👍🏿 I've tweaked my pickers, didn't realise `css_name` had been removed.

Regarding the strange behaviour, I believe this is possibly due to the use of `nvim_win_set_hl_ns` etc. I think that the highlights do not follow the highlight changes in the `0` namespace, so that if you set them before the colorscheme has loaded, then they won't be updated. I'm not 100% sure, but I was seeing behaviour like this in https://github.com/levouh/tint.nvim until the author delayed setting the namespace highlights till `VimEnter`.

**Comment by uga-rosa** [comment]
Hmmm. I see.
```vimhelp
nvim_win_set_hl_ns({window}, {ns_id})                   *nvim_win_set_hl_ns()*
    Set highlight namespace for a window. This will use highlights defined in
    this namespace, but fall back to global highlights (ns=0) when missing.

    This takes predecence over the 'winhighlight' option.

    Parameters: ~
        {ns_id}  the namespace to use
```
I will look into the solution.

**Comment by uga-rosa** [comment]
Maybe it's fixed. Can you try?

**Comment by akinsho** [comment]
@uga-rosa that now works *if I disable* `highlighter.auto_enable` for some reason if `auto_enable` is on, this highlighting weirdness happens. I don't know why adding what I presume is buffer highlights would trigger this behaviour

**Comment by uga-rosa** [comment]
https://github.com/uga-rosa/ccc.nvim/blob/cd1f6d2dedde0829df7b8713bfe02a37e97d6c7e/lua/ccc/config/init.lua#L43-L50
I'm trying to start it with VimEnter now, but I'm not sure if this is a good idea.
What happens if you change it to BufEnter or WinEnter?

**Comment by akinsho** [comment]
@uga-rosa I've tried setting it to `BufEnter` and it still causes my normal float highlight in floating windows to be affected

<img width="946" alt="image" src="https://user-images.githubusercontent.com/22454918/191913847-a61a2c4f-22f7-43bd-b2bc-47b24a0b112f.png">

I'm almost certain (with no actual proof) that there is a strange interaction when using `nvim_set_hl_ns` somehow either as a bug in nvim or a gotcha with that functionality. I looked through the code and noticed that the highlights are being set inside this plugin's hl namespace I haven't followed all the code through, but it seems likely somewhere in this setup the `NormalFloat` for windows is being affected somehow. Maybe floating windows accidentally or intentially inherit window ns highlights?

Note that all my floats are now affected (except ccc's pick window now).

**Comment by uga-rosa** [comment]
I see.
If you use CccHighlighterEnable manually without using auto_start, will it break?
I think I'll stop using win_set_hl_ns for the highlighter. I'll try to make a PR so they can try it out.

**Comment by akinsho** [comment]
@uga-rosa when I start with `auto_enable = false` my windows are fine, when I then run the command manually immediately after all my floating window normal backgrounds have been changed.

**Comment by akinsho** [comment]
I think I recall @levouh over in `tint.nvim` mentioning something about links not working in the highlight namespaces, maybe 🤔

**Comment by uga-rosa** [comment]
Since highlighter does not create as many highlights as ccc-ui, I tried to define highlights globally. Could you try #20?
