### ISSUE TITLE
hsluv support

### ISSUE THREAD

**Issue by leiserfg** [uga-rosa/ccc.nvim#2]
Hi @uga-rosa, how are you doing?
It will be nice to have hsluv color space support.
You can "borrow" one from here:
https://github.com/hsluv/hsluv-lua/blob/master/hsluv.lua

**Comment by uga-rosa** [comment]
This is the first I've heard of it, so I'll give it a little try. Thanks.

**Comment by uga-rosa** [comment]
My question is, is `hsl(0,0%,0%)` the expression format for HSLuv as for normal HSL? In the implementation I am considering now, HSL is replaced with HSLuv by activating the `use_hsluv` option, but I am wondering if this should be left as is.

**Comment by leiserfg** [comment]
No it is not,it's a different colorspace.

**Comment by uga-rosa** [comment]
Oh, I'm sorry. I was misguided. I'm not familar to css.
Hmmm...the name is the same as HSL...it's kinda weird that the numbers are different on the HSL slider and the hsl(H,S%,L%) on line 4.

**Comment by leiserfg** [comment]
Sorry if I didn't make it clear, hsluv is a colorspace, it just happens to have the same component names as hsl but it's way more uniform than it, so it's better for making color pallets and so. But you can't use it as a format if you wanna write CSS colors, so my proposal is to have it at another colorspace in the picker, not as a format to write the color into the document.

**Comment by uga-rosa** [comment]
The implementation of the function itself is not a problem, but if there is a name overlap, please wait a while because I need to adjust the UI a bit. Like putting the input method on top or something like that.

**Comment by uga-rosa** [comment]
HSLuv support done.
I have improved the mechanism considerably, making it very easy to add a color system.
