### ISSUE TITLE
[Feature request] LSP colors support when available

### ISSUE THREAD

**Issue by adelarsq** [uga-rosa/ccc.nvim#21]
The idea would be to use LSP colors support when available ([textDocument/documentColor](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentColor)!) or fallback for the default rules.

At moment for this I use [document-color.nvim](https://github.com/mrshmllow/document-color.nvim), that is an amazing plugin, but would be nice to use just one plugin for this.

**Comment by uga-rosa** [comment]
Can you try #23?

**Comment by uga-rosa** [comment]
Also, I would like to test it myself, so it would be helpful if you could tell me what the environment settings are.

**Comment by adelarsq** [comment]
Amazing!

>  Also, I would like to test it myself, so it would be helpful if you could tell me what the environment settings are.

I will test on next week with Flutter, but I think that with [CSS](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#cssls) will be easier to test.
