### ISSUE TITLE
`highlighter.lsp = true` is throwing error

### ISSUE THREAD

**Issue by lopi-py** [uga-rosa/ccc.nvim#27]
it happens whenever a lsp doesn't support documentColor
![image](https://user-images.githubusercontent.com/70210066/192916075-1d77fd2a-d0a2-4e99-a813-019014420f53.png)

**Comment by uga-rosa** [comment]
Maybe yes, can you try #26 to see if the same error occurs?

**Comment by lopi-py** [comment]
Its not working now because of this: https://github.com/uga-rosa/ccc.nvim/pull/26/files#diff-880ae09dec121ea1e4aacf066f0e2a3922ceeba2c7ca93eda3d0bc090f1eed03R136
You're returning inside a loop, also just an observation, when I enter to the buffer, it doesn't get highlighted, I think its because server takes a little to load
