### ISSUE TITLE
[Feature request] OKHSV colorspace support

### ISSUE THREAD

**Issue by musjj** [uga-rosa/ccc.nvim#28]
https://bottosson.github.io/misc/colorpicker/
HSV support would be really nice, I personally find them a lot more intuitive than HSL.
If possible OKHSV would be a superior choice (blog post explaining the differences: https://bottosson.github.io/posts/colorpicker/), but I haven't seen any Lua implementation so there might be a need to write it from a scratch.

**Comment by uga-rosa** [comment]
I will do it over the weekend.

**Comment by musjj** [comment]
Never mind, it seems that HSV support is already available, didn't read the help pages carefully enough.
But OKHSV support would definitely still be nice.

**Comment by uga-rosa** [comment]
done in 0776f0ed411e79e1f981b321e173b4c5fcf2400d

**Comment by musjj** [comment]
Thank you man, your plugin is really awesome!
