### ISSUE TITLE
Bug: Attempt to call field 'nvim_win_set_ln_ns'

### ISSUE THREAD

**Issue by pinpox** [uga-rosa/ccc.nvim#29]
I get the following error when running `CccPick` 

![image](https://user-images.githubusercontent.com/1719781/193284225-04706e45-19e1-4401-8e3f-8b518cb01dd5.png)

**Comment by uga-rosa** [comment]
Read the readme.
> If you use release version (0.7.2), use branch 0.7.2

**Comment by pinpox** [comment]
Didn't see that in the README. Would it be possible to make a release on GitHub? I'm packaging this plugin for the NixOS distribution and am not sure which version I should assume to be the latest stable release.

**Comment by uga-rosa** [comment]
I deleted it on [that day](e9d29bbb1aa2419942cf3df9cd201156c1b4db88) when 0.8.0 was released, but I had written it before that.
It's been less than a month since I made it, so it's practically a beta version. I think I have settled on some additional features, so it is certainly time to release it.
