### ISSUE TITLE
Filetype for the pick window

### ISSUE THREAD

**Issue by adelarsq** [uga-rosa/ccc.nvim#3]
Would be nice to add a filetype for the pick window, that are useful for customization.

On my case I did create a plugin with common ignored files for certain plugins: [ignored_files.vim](https://github.com/adelarsq/ignored_files.vim). One feature is to disable indent plugins for a list of filetypes.

So now the pick window shows like this:

![image](https://user-images.githubusercontent.com/430272/190277375-333d6b77-becc-4183-84b1-eb11336ed78a.png)

With filetype support would be like this:

![image](https://user-images.githubusercontent.com/430272/190277463-f9dae36a-53ff-4b6b-a534-7ab02a763190.png)

**Comment by uga-rosa** [comment]
Ok.
I set file type "ccc-ui".

**Comment by adelarsq** [comment]
@uga-rosa Thanks! 👍
