### ISSUE TITLE
Why did you rip off Max's plugin without paying tribute in the readme?!

### ISSUE THREAD

**Issue by molleweide** [uga-rosa/ccc.nvim#30]

**Comment by molleweide** [comment]
Are you kidding with me?

**Comment by uga-rosa** [comment]
You've got to be kidding me. I know there are multiple similar plugins, but not a single one I've seen referenced in either UI or implementation. Who is Max? [Here](https://colorizer.org)'s the site I was inspired by.

**Comment by molleweide** [comment]
https://github.com/nvim-colortils/colortils.nvim

To my eyes it is pretty much the exact same, but if you say so I have no reason not to believe you. However, you have to understand why I asked initially. 

Have a good day.
