### ISSUE TITLE
Getting highlighter.lua:118: Invalid buffer id: 1 when opening any file 

### ISSUE THREAD

**Issue by Almo7aya** [uga-rosa/ccc.nvim#33]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### Description

I just updated ccc.nvim from the main branch and now I'm getting this error whenever I open any file 

![image](https://user-images.githubusercontent.com/17254073/193708871-3cfb1e9b-d952-4b2b-a2e7-286bcd7a2af8.png)

### Environments

OS:
macOS 12.6 21G115 arm64
neovim: 
NVIM v0.9.0-dev-1214-ge54541f7f-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by almo7aya@Alis-MacBook-Pro.local

### Minimal reproducible full config

not sure how to replicate it or what is causing it, i'm using https://github.com/LunarVim/LunarVim and this is my config file https://github.com/Almo7aya/dotfiles/blob/master/.config/lvim/config.lua#L160

### Steps to reproduce

opening any file using :e [filename] or by telescope

### Expected behavior

works fine without any errors

### Actual behavior

getting: Error executing vim.schedule lua callback: .../site/pack/packer/start/ccc.nvim/lua/ccc/hig
hlighter.lua:118: Invalid buffer id: 1
 
and it does not go away until I press enter 7 or 8 times

**Comment by Almo7aya** [comment]
update: 
adding event = "BufRead" fixes the issue 
```lua
  {
    "uga-rosa/ccc.nvim",
    event = "BufRead",
    config = function()
      local ccc = require("ccc")
      ccc.setup({
        highlight_mode = "bg",
        highlighter = {
          auto_enable = true,
        },
      })
    end
  },

```

**Comment by uga-rosa** [comment]
I'm requesting a minimal config because this makes it difficult to isolate the cause. I'll have to provide an example.

**Comment by Almo7aya** [comment]
@uga-rosa 
the `check` branch is working fine, just tried it
