### ISSUE TITLE
Treesitter fails when CCC is lazyloaded

### ISSUE THREAD

**Issue by colin-heffernan** [uga-rosa/ccc.nvim#34]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### Description

Whenever I have CCC lazyloaded, Treesitter does not apply. Highlighting, indenting, nothing works.

### Environments

NixOS Unstable 22.11
Neovim Nightly 0.9.0

### Minimal reproducible full config

Manually place nvim-treesitter in the Start folder and ccc.nvim in the Opt folder in the packpath
```lua
local configs = require("nvim-treesitter.configs")
configs.setup {
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	}
}

local onFileOpen = function()
	vim.api.nvim_exec(
		[[
			packadd ccc-nvim
		]],
		true
	)	
	local ccc = require("ccc")
	ccc.setup {
		highlighter = {
			enable = true
		}
	}
end
vim.api.nvim_create_autocmd(
	{"BufRead","BufNewFile"},
	{
		callback = onFileOpen
	}
)
```

### Steps to reproduce

1) Open an existing file that would normally be highlighted with Neovim

### Expected behavior

Treesitter works as usual, with all the normal features, such as highlighting.

### Actual behavior

Treesitter fails to load. It throws no error messages, but it does nothing.

**Comment by uga-rosa** [comment]
```lua
require("nvim-treesitter.configs").setup({
    highlight = {
        enable = true,
    },
})

local function onFileOpen()
    vim.cmd("packadd ccc.nvim")
end

vim.api.nvim_create_autocmd({
    "BufRead",
    "BufNewFile",
}, {
    callback = onFileOpen,
})
```
We reproduced it in a smaller setting. It appears that the file type is not set. I will look into it.

**Comment by uga-rosa** [comment]
Fix in 814a7f560e364f92077f579d4fc25826e9717a9b.

**Comment by gegoune** [comment]
Seems like that commit errors on startup with:

```
               Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: .../site/pack/packer/start/ccc.nvim/lua/ccc/highlighter.lua:52: attempt to index field 'ft_filter' (a nil value)
stack traceback:
        .../site/pack/packer/start/ccc.nvim/lua/ccc/highlighter.lua:52: in function 'enable'
        .../site/pack/packer/start/ccc.nvim/lua/ccc/config/init.lua:58: in function <.../site/pack/packer/start/ccc.nvim/lua/ccc/config/init.lua:52>
```

With config:

```lua
require('ccc').setup {
  highlighter = {
    auto_enable = true,
    excludes = {'packer', 'DiffviewFileHistory' },
  },
}
```

**Comment by uga-rosa** [comment]
fixed
