### ISSUE TITLE
Close picker window on picker buffer leave

### ISSUE THREAD

**Issue by lopi-py** [uga-rosa/ccc.nvim#35]
### Request for other features

It's more comfortable, at least with some configuration like `autoclose` or something like that, it could also be nice to add to the default mappings to close the window with `<esc>`.

**Comment by uga-rosa** [comment]
Done in cd31ed4e40a542b24c5d157e00a81bfbb9b923ea.
The default settings for mapping are adjusted to me. You are free to set it as you wish.
