### ISSUE TITLE
Error when lazy-loading: a ttempt to index field 'ft_filter'

### ISSUE THREAD

**Issue by Avimitin** [uga-rosa/ccc.nvim#39]
Still getting same error if I am using lazy-loading:

```lua
use  {
    "uga-rosa/ccc.nvim",
    config = function()
      require("ccc").setup()
    end,
    cmd = {
      "CccPick",
      "CccHighlighterEnable",
    },
  },
```

* Error

```text
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:171: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim:Error executing Lua callback: ...im/site/pack/packer/opt/ccc.nvim/lua/ccc/highlighter.lua:52: a
ttempt to index field 'ft_filter' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:171: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:167>
        [string ":lua"]:1: in main chunk
```

_Originally posted by @Avimitin in https://github.com/uga-rosa/ccc.nvim/issues/37#issuecomment-1269289919_

**Comment by Avimitin** [comment]
Removing the lazy-loading can fix this issue. And after profiling, this plugin didn't delay startup time a lot. It is ok to just autoload ccc.nvim. So this issue can be just an reminder.

**Comment by uga-rosa** [comment]
I'm fine with it this time, but please be aware that I'm going to basically ignore any issue that doesn't use the template.
The latest version didn't fix it? It worked fine on my environment, even with delayed loading using cmd.
