### ISSUE TITLE
floating window border randomly changes when sliding colors

### ISSUE THREAD

**Issue by ghifarit53** [uga-rosa/ccc.nvim#4]
Hi uga-rossa, thanks for this lovely color picker plugin! Unfortunately though, I encounter an odd issue. Whenever I'm moving my slider, the border color of the floating window suddenly changes. I've provided the steps here that atleast always consistently result in the same behavior on my machine, also a GIF

## Expected behavior
the window border color shouldn't change

## Actual behavior
Window border color changes randomly in some occasion

## Configuration
```lua
-- color picker
use {
  "uga-rosa/ccc.nvim",
  cmd = "CccPick"
}
```

## Steps to reproduce
1. Open ccc window and use RGB as input
2. Move the Red slider to the right end, then do the same for Green and Blue
3. When finally sliding in Blue, the border color changes itself

## Attachments
![ccc-border-color](https://user-images.githubusercontent.com/59758342/190308141-3675c300-eb25-4d05-9fdb-ab918cbe717b.gif)

**Comment by uga-rosa** [comment]
This is a phenomenon that I have also confirmed, but it should not happen due to the way the plugin works. Therefore, I think it is a bug in the main unit.

**Comment by uga-rosa** [comment]
I'll put it in the README as a known bug.

**Comment by uga-rosa** [comment]
Maybe fixed.
The cause would be I cannot set highlight to namespace, so highlights are not cleared, accumulated.
