### ISSUE TITLE
The very first buffer does not get auto highlighted

### ISSUE THREAD

**Issue by otommod** [uga-rosa/ccc.nvim#40]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### Description

Even with `highlighters.auto_enable` set to `true`, the very first buffer (the one with the file given in the command line) does not get highlighted.  I'm guessing the `BufEnter` event does not fire or it has already fired by the time `require("ccc").setup` runs

### Environments

Arch Linux
NVIM v0.8.0

### Minimal reproducible full config

```lua
require("packer").setup(function(use)
  use {"uga-rosa/ccc.nvim", config = function()
    require("ccc").setup {highlighter = {auto_enable = true}}
  end}
end)
```

### Steps to reproduce

```sh
nvim foo.css
```

### Expected behavior

The colors in `foo.css` get highlighted

### Actual behavior

The colors do not get highlighted

**Comment by uga-rosa** [comment]
This issue is closed due to incomplete "Minimal reproducible full config" and "Steps to reproduce". Please check again and reopen with the correct corrections.
