### ISSUE TITLE
FR: Support modern CSS color notation

### ISSUE THREAD

**Issue by chrisgrieser** [uga-rosa/ccc.nvim#43]
### Request for other features

[modern css color notation](https://stylelint.io/user-guide/rules/list/color-function-notation/#modern) leaves out the commas for `rgb` and `hsl` and the like. 

<img width="759" alt="Pasted image 2022-10-07 01 49 28" src="https://user-images.githubusercontent.com/73286100/194438304-bcef3e36-ce66-443b-b112-ebe16c14c36e.png">

**Comment by uga-rosa** [comment]
I see.
BTW, do you have `highlightrt.lsp = false`? I think it will color if you use LS.

**Comment by chrisgrieser** [comment]
> I see.
BTW, do you have highlighter.lsp = false? I think it will color if you use LS.

No, I haven't. I have coc-css, but don't get any color highlighting through it?

**Comment by uga-rosa** [comment]
Ah, ok. You need nvim-lsp for this feature.

**Comment by chrisgrieser** [comment]
thanks for the quick implementation 🥳 

small follow-up issue: `hsla()` notation with a `/` for the alpha value seems to be missing, even though it does work for `rgba`
<img width="955" alt="image" src="https://user-images.githubusercontent.com/73286100/194575006-3699fa51-5c6e-4b25-a29c-ade655a4f103.png">

**Comment by chrisgrieser** [comment]
thank you so much. Awesome plugin, btw!
