### ISSUE TITLE
[Feature] Add support for RGB format with alpha channel

### ISSUE THREAD

**Issue by FollieHiyuki** [uga-rosa/ccc.nvim#45]
### Request for additional color space

It would be nice to have support for RGBA format (for both the picker and the highlighting). It's literally just RGB with alpha channel, often represented either as `#RRGGBBAA` (described in [CSS Color Module Level 4](https://w3c.github.io/csswg-drafts/css-color-4/#hex-notation)) or an int value `0xRRGGBBAA`.

Note that some applications use sRGB so the int would be `0xAARRGGBB`. I don't know how we can distinguish both forms in a buffer without LSP when the user invoke the picker though.

**Comment by uga-rosa** [comment]
I was struggling to deal with the `0xFFFFFFFF`, but it seemed impossible without LSP, so I gave up!
You can try `dev` branch for 8/4 digits notation of HEX.
