### ISSUE TITLE
Cccpick can't be ran more than once?

### ISSUE THREAD

**Issue by miversen33** [uga-rosa/ccc.nvim#5]
Im almost certain I am doing something wrong.
I can open the floating window with `:CccPick`, however if I then `:q`, I cannot reopen `:CccPick` without restarting neovim. Below is a gif to show this in action. Note: `<CR>` does work, but forces an insert of whatever code I have up. If I _don't_ want to insert anything, I would expect the `:q` behavior to work as expected.

![cccpick-error](https://user-images.githubusercontent.com/2640668/190413135-9ff2daf4-3be0-43ee-8bec-603b4e70e71d.gif)

Im not sure what info would be helpful to you so here is what I could find for "useful" info (what I usually provide in bug reports)

Neovim Info

```
$ nvim --version
NVIM v0.8.0-dev-1060-g22a88c425
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/miversen/git/neovim/build/cmake.config -I/home/miversen/git/neovim/src -I/home/miversen/git/neovim/.deps/usr/include -I/usr/include -I/home/miversen/git/neovim/build/src/nvim/auto -I/home/miversen/git/neovim/build/include
Compiled by miversen@dev-miversen

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/neovim/share/nvim"

Run :checkhealth for more info
```

Plugin Info (currently pointing at origin/main HEAD)
```
$ git rev-parse HEAD
c4861169f26f642cb445dea819faf02f9e2a5ae1
```

Thoughts? Can I provide anything else useful for you? Am I doing something wrong?

**Comment by ghifarit53** [comment]
Can confirm this also happens on me, `:CccPick` doesn't reopen when  previously being closed with `:q`, though you can just press `q` to close the window

**Comment by uga-rosa** [comment]
Please don't use :q because quit hooks into a lot more than just closing. This did not close properly, so the function to avoid multiple openings is malfunctioning.

**Comment by miversen33** [comment]
> Please don't use :q because `quit` hooks into a lot more than just closing. This did not close properly, so the function to avoid multiple openings is malfunctioning.

I can accept this, though I would *highly* advise this is documented somewhere on the readme as this _will_ be a recurring issue.

**Comment by uga-rosa** [comment]
I changed the mechanism so that it can be reopened after closing it with :q.
