### ISSUE TITLE
`:CccPick` removes character in front of color & adds Alpha

### ISSUE THREAD

**Issue by chrisgrieser** [uga-rosa/ccc.nvim#60]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### Description

`:CccPick` removes character in front of the color (tested it, it's not spaces, but any character). It also adds alpha by default now.

Both behaviors did not occur in the latest commit from a few days ago.

### Environments

```
macOS 12.5.1 (M1)
neovim 0.8.0 (homebrew)
```

### Minimal reproducible full config

The `minimal.vim` file does not work. I removed my entire nvim config, and placed nothing but the linked `minimal.vim` file in there. I also removed all plugins from `~/.local/share/nvim/site/pack/packer`. Upon calling `:CccPick` it errors: `E492: Not an editor command: CccPick`.

So I tried this as minimal config:
```lua
opt.termguicolors = true
local ccc = require("ccc")
ccc.setup{}
```

### Steps to reproduce

1. use the minimal config from above
2. use `:CccPick`

### Expected behavior

using the picker should not remove preceding characters.

### Actual behavior

using the picker removes the preceding character.

### Additional context

After a bunch of trial and error, I could figure out that explicitly disabling LSP for highlighting (`highlighter.lsp` set to false) seems to fix this issue.

**Comment by uga-rosa** [comment]
minimal.vim works in my environment. My environment is linux, so I guess it would work on mac. By the way, I use `nvim -u utils/minimal.vim` to start.

Fixed in f1ca498dc7f706df96dde4eadfa7a8afa31a8f98.

**Comment by chrisgrieser** [comment]
thanks! the removal of the preceding character has been fixed by `f1ca498`, but the alpha is still added by default

**Comment by uga-rosa** [comment]
As mentioned earlier, the display of the alpha value is not a bug and cannot be automatically determined, so adding an option to control the behavior is the limit.

**Comment by chrisgrieser** [comment]
I see, yeah in that case this issue can be regarded as fixed I guess. I'll open a separate FR for the alpha output
