### ISSUE TITLE
FR: Alpha Slider

### ISSUE THREAD

**Issue by chrisgrieser** [uga-rosa/ccc.nvim#62]
### Request for other features

Follow up to #60.

Right now, `highlight.lsp = true` results in adding the alpha even though the color under the cursor does not have alpha when using `:CccPick`.

An alpha-slider option like you suggested indeed sounds like a good solution to this:
> It would be possible to add option alphaslider to make the display of the alpha slider configurable when the ui is opened. ("auto", "show", "hide").

**Comment by uga-rosa** [comment]
Done in 27c5904a60d1cebddfe6e246dd7f7df174ad7394.
