### ISSUE TITLE
Cannot use ccc.nvim WSL2 0.2.1 |  neovim 0.9.0-dev | Ubuntu 20.04

### ISSUE THREAD

**Issue by dantearaujo1** [uga-rosa/ccc.nvim#64]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### Description

When i try to :CccPick it returns this:
 
![image](https://user-images.githubusercontent.com/21104508/196665943-be528f6a-eedb-4355-8359-a007f8f99807.png)

Don't know what to do.

### Environments

Windows 11 using Wsl2 with Ubuntu 20.04

### Minimal reproducible full config

Could not make it work using minimal config provide in example

### Steps to reproduce

Enter command mode and using CccPick

### Expected behavior

Open ColorPick

### Actual behavior

Gives an error

**Comment by uga-rosa** [comment]
It looks like you did some extra configuration, but I can't reproduce it, and I don't intend to respond to bug report issues without a minimum configuration.
Also, what do you mean that minimal config doesn't work, I have confirmed that it works properly with `nvim -u utils/minimal.vim`.

**Comment by dantearaujo1** [comment]
u can close now, it seems that i didn't call ccc.setup anywhere in my config, sorry and thanks for your time
