### ISSUE TITLE
CccPick fails after session switching

### ISSUE THREAD

**Issue by coffebar** [uga-rosa/ccc.nvim#65]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

I'm using plugin for session switching and i noticed after installing ccc.nvim that it fails after session loading.
It seems that the check that the buffer exists is missing.

Possible i can help to fix this issue.

### Environments

Linux x86
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Minimal reproducible full config

https://github.com/coffebar/dotfiles

### Steps to reproduce

Open file with color, open color piker, switch session to other project, open other file with color, open color piker for it.

### Expected behavior

Color piker always opens.

### Actual behavior

Color picker works in first project, but on second it fails with this error:
```
Error executing Lua callback: ...m/site/pack/packer/start/ccc.nvim/lua/ccc/utils/init.lua:55: Invalid buffer id: 27
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        ...m/site/pack/packer/start/ccc.nvim/lua/ccc/utils/init.lua:55: in function 'set_lines'
        ...hare/nvim/site/pack/packer/start/ccc.nvim/lua/ccc/ui.lua:201: in function 'update'
        ...hare/nvim/site/pack/packer/start/ccc.nvim/lua/ccc/ui.lua:136: in function 'open'
        ...hare/nvim/site/pack/packer/start/ccc.nvim/plugin/ccc.lua:9: in function <...hare/nvim/site/pack/packer/start/ccc.nvim/plugin/ccc.lua:8>
```
If reopen nvim on second project again - color picker works. But after switching to other project - it is broken again.

**Comment by coffebar** [comment]
I made a fix. 
Video demo:

[rec.webm](https://user-images.githubusercontent.com/3100053/206897120-03d47deb-04c1-4cef-a4a1-2ee2dbfa9ca1.webm)


Steps on video:
Open nvim
See "uga-rosa/ccc.nvim" installed via packer
Open file with color, open color picker
Switch session to other project
Switch back to first file, open color picker
See color picker failed to open
Change plugin "uga-rosa/ccc.nvim" to fork with fix `{ "coffebar/ccc.nvim", branch = "session_switching_fix" }`
Run PackerSync
Re-open nvim
Repeat steps with project switching
Color picker now works fine

**Comment by coffebar** [comment]
I now noticed a small flaw in the config: You will need to re-open editor (run command `nvim -nu minimal.lua style.css` twice), first time it will install dependencies, but will be ready on second run. 
Hope everything will work out for you!

**Comment by uga-rosa** [comment]
Thank you. I was able to reproduce it.

**Comment by coffebar** [comment]
@uga-rosa Good! Check my PR

**Comment by uga-rosa** [comment]
I already reviewed. Please check.
