### ISSUE TITLE
CccPick and highlighter won't detect multiple hsl or multiple rgb colors in the same line

### ISSUE THREAD

**Issue by arsmoriendy** [uga-rosa/ccc.nvim#68]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

[![asciicast](https://asciinema.org/a/wAnJe1vDQawXGjCRNg6zB3kYu.svg)](https://asciinema.org/a/wAnJe1vDQawXGjCRNg6zB3kYu?t=7)

### Environments

fedora x86
neovim 0.8.3
                packer.nvim - Total plugins: 10
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 • Comment.nvim
 • ccc.nvim
 • gruvbox.nvim
 • indent-blankline.nvim
 • lualine.nvim
 • nvim-colorizer.lua
 • nvim-treesitter
 • nvim-web-devicons
 • packer.nvim
 • twilight.nvim

### Minimal reproducible full config

did :PackerCompile with this config
```lua
-- PLUGINS --
return require("packer").startup(function(use)
  use "wbthomason/packer.nvim"
  use {
    "uga-rosa/ccc.nvim",
    config = function()
      require("ccc").setup()
    end
  }
end}
```

### Steps to reproduce

insert multiple hsl or multiple rgb colors in the same line and enable highlighter

### Expected behavior

detects and highlights colors

### Actual behavior

only detects and highlights the first color

**Comment by uga-rosa** [comment]
Thank you for reporting.
Please check it out, I fixed it.
