### ISSUE TITLE
[Feature Suggestion] Add a picker to colorize static entries

### ISSUE THREAD

**Issue by delphinus** [uga-rosa/ccc.nvim#69]
I wrote a picker ([link][]) to colorize any string with setting a table in `setup()`.

[link]: https://github.com/delphinus/dotfiles/blob/2c87826171d4397767e935e8db681aac4a6cff01/.config/nvim/lua/core/utils/ccc.lua

```lua
require("ccc").setup {
  picker = {
    require "ccc.picker.rgb",
    require "core.utils.ccc" {
      red = "#BF616A",
      green = "#A3BE8C",
      blue = "#81A1C1",

      ……

    }
  },
}
```

<img width="548" alt="スクリーンショット 2023-02-26 19 18 46" src="https://user-images.githubusercontent.com/1239245/221404713-d7acabbd-8587-4869-8c5c-06a933e6faab.png">

Can you merge this feature when I issue it as a PR?

**Comment by uga-rosa** [comment]
The nice thing about this plugin is that you can extend the functionality without having to make changes to the main body, as you are doing.
Be that as it may, a user-definable picker could certainly be useful, and PR would be welcome :)

**Comment by uga-rosa** [comment]
Please add it as `picker/custum_table.lua`. It would also be helpful if you could update doc, test (`picker/picker_spec.lua`) and `init.lua`. The test can be done without if you don't know how to write it.

**Comment by delphinus** [comment]
@uga-rosa I wrote the original logic with using Vim's regex pattern because it can detect boundaries of words with `\<` / `\>`. But other pickers are using Lua's one including the `exclude_pattern` option.

1. Use Vim's regex even so.
   - pros: It can detect word boundaries precisely.
   - cons: It cannot use `exclude_pattern`, or should use Vim's regex in it unlike any other picker.
2. Use Lua's regex.
   - pros: Code still keeps consistency.
   - cons: It cannot detect word boundaries. When I set `"red"` as a red color, `"Alfred"` will be colored over its the last 3 letters.
     - Of course, `exclude_pattern` can reduce this problem.

Which should we use? How do you think?

**Comment by uga-rosa** [comment]
When I added picker/css_name, I noticed the word boundary issue and added exclude_pattern for compatibility. However, vim's regular expressions are indeed powerful and I would like to use them if I didn't have to worry about compatibility.
So please use the lua pattern for now. I may make some destructive changes when I release v2.

**Comment by delphinus** [comment]
OK, I will use Lua's one. Thank you.

**Comment by uga-rosa** [comment]
Oh, I'm sorry. I was confused myself, but I'm already using vim regexp internally in some parts, like utils/pattern.lua. So the logic is fine as it is.
I'll remove exclude_pattern nearby.

**Comment by delphinus** [comment]
I see. I will keep both regexes in it, Vim's one and Lua's one. For example, when I want to colorize `"red"` and `"blue"`, this code below can manage them.

```lua
-- colorize by this vim regexp
self.vim_regexp = [[\<\(red\|blue\)\>]]

-- and use lua regexp to deal with `exclude_pattern` option
local ex_pat = config.get("exclude_pattern")
local lua_regexp = [[(red|blue)]]
self.exclude_pattern = utils.expand_template(ex_pat.custom_entries, lua_regexp)
```

I will rewrite the logic with such code.

**Comment by delphinus** [comment]
hmm, I noticed the logic above is broken when the keys in entries include special characters that has different meanings between Lua and Vim. For example, escape characters are `%` in Lua and `\` in Vim.

```lua
require("ccc").setup {
  picker = {
    require "ccc.picker.custom_entries" {
      blue = "#0000FF",  -- this works good
      ["%w+red"] = "#FF0000", -- this is valid in Lua, but invalid in Vim.
    },
  },
}
```

As a suggestion, we should write in doc that this feature does not support any special character. And it should match with `\V` (very magic) in Vim regexp.

Of course, we can convert each Lua regexp into Vim one beforehand, but I think it is “too much”. How do you think? @uga-rosa

**Comment by uga-rosa** [comment]
Yes, I agree. Conversion is too much.
Please write so in doc, be `very nomagic` too. I don't want this picker to be that complicated.
