### ISSUE TITLE
`CccHighlighterToggle` and CccHighlighterEnable` doesn't work when set auto auto_enable filetypes

### ISSUE THREAD

**Issue by JuanZoran** [uga-rosa/ccc.nvim#71]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

I found that when I set the auto_enable option and filetypes, then the `CccHighlighterToggle` command will not work anymore
this is my configuration for that: 
```lua
 return { "uga-rosa/ccc.nvim",
    cmd = {
        'CccHighlighterToggle',
        "CccPick",
        "CccConvert",
    },
    ft = { 'css', 'html' },
    config = function(plugin)
        local ccc = require("ccc")
        local mapping = ccc.mapping
        ccc.setup {
            highlighter = {
                auto_enable = true,
                filetypes = plugin.ft,
            },
            mappings = {
                j = mapping.decrease1,
                h = mapping.toggle_input_mode,
                i = 'k',
            }
        }
    end,
}
```
it will auto-enable when I open a new HTML and CSS file, but in a Lua file , I try to use `CccHighlighterEnable`, it doesn't work
> CccPicker is still working...

so I have to change my configuration for that now, for example:
```lua
return {
    "uga-rosa/ccc.nvim",
    cmd = {
        'CccHighlighterToggle',
        "CccPick",
        "CccConvert",
    },
    ft = { 'css', 'html' },
    config = function(plugin)
        local ccc = require("ccc")
        local mapping = ccc.mapping
        ccc.setup {
            mappings = {
                j = mapping.decrease1,
                h = mapping.toggle_input_mode,
                i = 'k',
            }
        }
      vim.api.nvim_create_autocmd('Filetype', {
       patten = plugin.ft,
       command = 'CccHighlighterEnable'
})
    end,
}
```

### Environments

Ubuntu22.04LTS, kitty latest version

### Minimal reproducible full config

just as the description saying

### Steps to reproduce

set auto_enable filetypes then try to use the CccHighlighterEnable command

### Expected behavior

The CccHighlighterEnable command should add highlights in the current buffer

### Actual behavior

nothing is changed

### Additional context

nop

**Comment by uga-rosa** [comment]
Please give me a minimal reproducible **full** config. I don't even know what plugin manager you are using.

**Comment by uga-rosa** [comment]
Ah, I see what you mean, it must be because of the filter generated from filtypes in CccHighlighterEnable. should I make sure that filetypes is only referenced when auto_start is used?

https://github.com/uga-rosa/ccc.nvim/blob/9738eb1d47bdb5d808f1c427e1c2db3dadae00b7/lua/ccc/highlighter.lua#L75

**Comment by uga-rosa** [comment]
Changed in e66fd3a18eff0c9c4c772a5e5fd9ad68753c6d8e.

**Comment by JuanZoran** [comment]
Oh nice, I just tried that, and it works properly! Thanks for that.

> I am sorry for I didn't reply you in time :(
