### ISSUE TITLE
Bug: Last commit breaks `:CccPick`

### ISSUE THREAD

**Issue by chrisgrieser** [uga-rosa/ccc.nvim#73]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

`:CccPick` does not work anymore

### Environments

```
macOS 13.2.1 (M1)
neovim 0.8.3 (homebrew)
Neovide 0.10.3 (homebrew)
```

### Minimal reproducible full config

I used the provided `minimal.vim` with no config changes.

`:CccHighlightEnable` etc. works, `:CccPick` does not.

### Steps to reproduce

- use the latest commit 4869fb3
- run `:CccPick`

### Expected behavior

the color picker should work

### Actual behavior

every time I run `:CccPick`, I get this, regardless of the config. Whether I use `minimal.vim` or my own config, the result is the same.

![CleanShot 2023-03-12 at 12 14 01](https://user-images.githubusercontent.com/73286100/224540949-b3873f67-1b89-40b5-b87e-73f7f22528ae.png)

### Additional context

With the previous commit `d17dabd`, everything works.

**Comment by uga-rosa** [comment]
Sorry, and thank you for reporting. I fixed.
