### ISSUE TITLE
[Question] Excluding short hex from highlighting

### ISSUE THREAD

**Issue by akinsho** [uga-rosa/ccc.nvim#76]
Hi @uga-rosa, 

Sorry for the question but having searched through similar issues, most closely related of which is https://github.com/uga-rosa/ccc.nvim/issues/14. I couldn't/cannot get this plugin to stop highlighting any numbers preceded by a # e.g. `#236` for example which could be a PR or issue number on GH and not a hex color. In general I don't want it highlight any hex colors that aren't >= 6.

I tried using the `exclude_pattern` option mentioned in that issue (it's undocumented btw, just mentioning so you're aware) for example:
```lua
        hex = {
          '%s#%x%x%x%s+',
          '[%w_]#%x%x%x',
          '[%w_]#%x%x%x%x%x%x',
        },
```
but the following text in a `lua` file with the highlighter enable still highlights ` -- partial fix for #391` the `#391` is still highlighted unfortunately.

I'm pretty sure that lua pattern works as I've tested that it would match the pattern but it doesn't stop the highlighting.

**Comment by uga-rosa** [comment]
Please use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions), not issue, for questions.
