### ISSUE TITLE
disable highlight when visual selection touches color

### ISSUE THREAD

**Issue by Machine-Maker** [uga-rosa/ccc.nvim#78]
### Request for other features

When selecting with visual mode, the highlighting can sometimes mess with the text color, making the highlighted text less readable. Like if the normal text color is white, `ccc.nvim` changes the text color to black if its a light color, but then visual mode keeps that dark text color.

Is there some way for a highlight for a specific color string to turn off when visual mode crosses over it?

**Comment by uga-rosa** [comment]
How about setting `highlight_mode` to `'fg'` or hooking enable/disable to/from visual mode? You can do it with ModeChanged.

Here's the simplest example.
```lua
require('ccc').setup({
  highlight_mode = 'fg'
})
```
or
```lua
-- Enter visual mode
vim.api.nvim_create_autocmd("ModeChanged", {
  pattern = "*:[vV\x16]",
  callback = function()
    vim.cmd.CccHighlighterDisable()
  end,
})
                                             
-- Leave visual mode
vim.api.nvim_create_autocmd("ModeChanged", {
  pattern = "[vV\x16]:*",
  callback = function()
    vim.cmd.CccHighlighterEnable()
  end,
})
```

**Comment by uga-rosa** [comment]
Is there a significant difference in experience between erasing all highlights while in visual mode and carefully determining and erasing only those that overlap with the selection? If it only makes it look a little better, I'm not sure it would be worth the cost of future maintenance.

**Comment by Machine-Maker** [comment]
Well yeah, the benefit would be it looking better. I don't really see a benefit other than that. I don't know what the maintenance cost would be for such a feature, but if its too much to be worth it, then 🤷 .
