### ISSUE TITLE
VSCode-like color square

### ISSUE THREAD

**Issue by pandasoli** [uga-rosa/ccc.nvim#79]
### Request for other features

The color picker in **CSS** files in **VSCode** are seems as a colored square that when you click on it the color picker opens.

Example:
![https://user-images.githubusercontent.com/13795438/29198740-4ecbeeb6-7e79-11e7-9dc6-0d612b75cba0.jpg](https://user-images.githubusercontent.com/13795438/29198740-4ecbeeb6-7e79-11e7-9dc6-0d612b75cba0.jpg)

Could you add this style option?  
I think it makes the code organized and with no much visual garbage.

**Comment by pandasoli** [comment]
Just a question. Why when I pick in RGB the output is in HEX?

**Comment by uga-rosa** [comment]
I do not think it is necessary. The current design matches well with the structure of the color space, which is a vector. HSL color space would provide a similar experience.

The cost of maintaining a document with similar content in two formats with no discrepancies is much higher than you think.
As I mentioned in the readme, see doc for details.
