### ISSUE TITLE
Open picker on <leader> on top of the color

### ISSUE THREAD

**Issue by pandasoli** [uga-rosa/ccc.nvim#80]
### Request for other features

I think it would be very useful to open the color picker when we press `<leader>` at the top of a color.  
It would not make `:CccPicker` useless as we'd still need it to pick a color if we don't have one in a specific place.

**Comment by uga-rosa** [comment]
I'm not sure what you are getting at, but I have no intention of providing a global mapping without the \<Plug> prefix.
