### ISSUE TITLE
Question regarding highlighter foreground mode

### ISSUE THREAD

**Issue by prss-ad** [uga-rosa/ccc.nvim#89]
Hi, 
I read this in the docs:

  highlight_mode ~
  "fg" | "bg" | "foreground" | "background"
  Default: "bg"
	  Option to highlight text foreground or background. It is used to
	  output_line and highlighter.

So i assumed it means i can change the highlight mode of the buffer to highlight the text not the background of it.
I could not get it to work. May be i misunderstood the docs.
I tried to pass to setup { highlight_mode='fg' } but still the background of text gets colored.
I also tried { highlighter = { highlight_mode = 'fg'}} with no luck.
Am i missing something or it is not supported?

Thanks for this excellent color picker by the way.
best regards.

**Comment by uga-rosa** [comment]
- fg
![image](https://github.com/uga-rosa/ccc.nvim/assets/82267684/acc7cc03-fe3a-4d30-b735-bab4835cb6fd)
- bg
![image](https://github.com/uga-rosa/ccc.nvim/assets/82267684/c24f588d-3d69-4290-9c7c-cb819220eab7)

**Comment by uga-rosa** [comment]
I guess setup function is not called before reading plugin/ccc.lua, but the plugin manager issue is not my issue to solve.

**Comment by uga-rosa** [comment]
If you can provide a procedure to reproduce this without the plugin manager, I'll fix it.

**Comment by prss-ad** [comment]
Thank  you for your help. I've been trying other configurations including other plugin managers. I believe you are right. There is an issue when using Lazy. I have not figured out what it is yet. 
Sorry for the bother. 
Have a nice weekend. 
best regards.
