### ISSUE TITLE
Incredible plugin...

### ISSUE THREAD

**Issue by 9mm** [uga-rosa/ccc.nvim#90]
### Request for additional color space

Truly phenomenal, I was trying so many plugins which were really weak, and I was extremely surprised you have every color space I could ever want. Huge props for putting in HSLuv. Thank you for your hard work 🙏🏼

**Comment by uga-rosa** [comment]
Thank you!
Just so you know, I'm always open for GitHub sponsors! 😉

**Comment by 9mm** [comment]
ok Ill send $50

**Comment by uga-rosa** [comment]
Thank you! I'm very happy 😘
