### ISSUE TITLE
:CccConvert deletes Alpha channel information -- Please fix

### ISSUE THREAD

**Issue by edwestfieldjr** [uga-rosa/ccc.nvim#91]
### Request for other features

The `:CccConvert` command does not preserve and removes all alpha channel information when toggling between color formats. For example: `#ff0004a` is converted to `rgb(255 0 0)` and not to `rgb(255 0 0 / 29%)`. Please fix so that alpha channel info is preserved in the conversion. Thanks

**Comment by uga-rosa** [comment]
Thanks for the report. Fixed.
Now `#ff00004a` should be `rgb(255 0 0 / 29%)` and `#ff0000` should be `rgb(255 0 0)
`.
