### ISSUE TITLE
Do not update the highlight color or add debounce parameters in insert mode.

### ISSUE THREAD

**Issue by Innei** [uga-rosa/ccc.nvim#92]
### Request for additional color space

When I am writing code, the highlighting of tailwindcss keeps flickering in insert mode.

https://github.com/uga-rosa/ccc.nvim/assets/41265413/5d9124ff-28df-4888-a691-98e5d265e7f4

**Comment by uga-rosa** [comment]
Sorry for the late reply. I've been traveling.
I try to reduce flickering as much as possible in highlighting with picker, but I didn't include that in highlighting with lsp. I will try to fix it.

**Comment by Innei** [comment]
Thank you!

**Comment by uga-rosa** [comment]
Updated.
Flickering has been reduced.
I have also added highlight.update_insert, please try it.
