### ISSUE TITLE
Textobject for highlighted colors

### ISSUE THREAD

**Issue by chrisgrieser** [uga-rosa/ccc.nvim#95]
### Request for other features

Maybe a bit of a wild idea, but quite often I thought that a text object for the highlighted colors would be useful. For example, to copy a color value directly to apply it somewhere else: assuming `#` as the keymap for it, you would copy a color via `y#`. 

While this plugin's focus is certainly not text objects, I think it makes more sense to implement such a feature via this plugin instead of a textobj plugin, since it already has all the information on the position of the highlighted colors.

**Comment by uga-rosa** [comment]
Add `<Plug>(ccc-select-color)` in operator-pending mode.

**Comment by chrisgrieser** [comment]
Thank you so much for the quick implementation! 😊 

A minor issue with the object: Apparently, it only works when the cursor is standing on a color. However, vim's (characterwise) text objects are forward-seeking, meaning that if the cursor is not standing on a text object, it automatically looks forwards until it can find one.

**Comment by uga-rosa** [comment]
I diverted the mechanism of `:CccPick`, so it only detects under the cursor. `ui:select_color()` in `ui.lua` is the implementation. PR is welcome, but the logic may need to be modified.
