### ISSUE TITLE
Support color pattern like 'FFFFFF'

### ISSUE THREAD

**Issue by gu-fan** [uga-rosa/ccc.nvim#97]
### Request for additional color space

the color pattern in godot is 'FFFFFF' like, and is not revealed with CCC

**Comment by uga-rosa** [comment]
Sorry, I don't know godot.

Please let me know if you know specifications. However, I will not be able to respond right away as I am busy with university graduation coming up.

Users can also add pickers, etc. in the settings without having to build them into the main unit.

**Comment by gu-fan** [comment]
well, seems not a big problem, 
I changed all the color text to '#FFFFFF' which godot also recongized.
