### ISSUE TITLE
Setting for HEX colors casing

### ISSUE THREAD

**Issue by MariaSolOs** [uga-rosa/ccc.nvim#98]
_I'm not sure if this is already supported_

I personally prefer using uppercase in hex colors (e.g. `#FFFFFF` instead of `#ffffff`). It seems like this plugin will always insert hex colors with lowercase letters. It would be nice for this to be configurable :)

**Comment by uga-rosa** [comment]
It is a reasonable proposal. I think this is a feature that needs to be implemented at some point, but I've been putting it off until someone else expresses a desire for it ;P

**Comment by uga-rosa** [comment]
Done.
You can use `ccc.output.hex.setup()`.

```lua
local ccc = require("ccc")

ccc.output.hex.setup({ uppercase = true })
ccc.setup({
  ...
})
```

**Comment by MariaSolOs** [comment]
Works great, thanks a lot @uga-rosa! <3
