### ISSUE TITLE
Sliders aren't highlighted if `winhl` is set in an autocmd 

### ISSUE THREAD

**Issue by backdround** [uga-rosa/ccc.nvim#99]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### I investigated.

- [X] I have read README.md, help documentation, and searched past issues but no solution.

### Description

Sliders aren't highlighted when the autocmd is set:
```lua
vim.api.nvim_create_autocmd({ 'CursorMoved', 'TextChanged', }, {
  callback = function()
    vim.wo[0].winhl = vim.wo[0].winhl
  end
})
```
![image](https://github.com/uga-rosa/ccc.nvim/assets/17349169/665bcbcc-dd5b-4d1c-9571-f80a10f84917)

### Environments

OS: Updated archlinux
Nvim: v0.10.0-dev-2246+gf4b3636f24 (almost latest commit)

### Minimal reproducible full config

```vim
set termguicolors

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/autoload/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'uga-rosa/ccc.nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

lua <<EOF
local ccc = require("ccc")
local mapping = ccc.mapping

ccc.setup({})

-- Inserted part:
vim.api.nvim_create_autocmd({ 'CursorMoved', 'TextChanged', }, {
  callback = function()
    vim.wo[0].winhl = vim.wo[0].winhl
  end
})

require("lspconfig").cssls.setup({})
EOF
```

### Steps to reproduce

Launch `:CccPicker` with the config above

### Expected behavior

Sliders are highlighted regardless of the assignment of `vim.wo[0].winhl = vim.wo[0].winhl`

### Actual behavior

Sliders aren't highlighted

### Additional context

It might relate to the latest neovim version (I didn't tested it on older neovim versions)

**Comment by uga-rosa** [comment]
This plugin uses `nvim_win_set_hl_ns`.
Perhaps this association will be removed by setting `winhl`.

```help
nvim_win_set_hl_ns({window}, {ns_id})                   *nvim_win_set_hl_ns()*
    Set highlight namespace for a window. This will use highlights defined
    with |nvim_set_hl()| for this namespace, but fall back to global
    highlights (ns=0) when missing.

    This takes precedence over the 'winhighlight' option.

    Parameters: ~
      • {ns_id}  the namespace to use
```

**Comment by backdround** [comment]
You are right. I checked it with the following code and figured out that setting highlights by one way overrides all highlights set by another way

Code for tests:
```lua
local ns = vim.api.nvim_create_namespace("UserTestHighlight")
vim.api.nvim_set_hl(ns, "Function", { fg = "#00FF66" })

vim.keymap.set("n", "<C-w>", function()
  vim.api.nvim_win_set_hl_ns(0, ns)
end)

vim.api.nvim_create_autocmd({ 'CursorMoved', 'TextChanged', }, {
  callback = function()
    vim.wo[0].winhl = "String:"
  end
})
```
